name: "example"
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Script Kit
        uses: johnlindquist/kit-action@main
        with:
          # The name of a script in your ./scripts dir
          script: "example-script"
          # Space-separated string arguments passed to each "await arg()"
          args: "https://johnlindquist.com/images/logo/john@2x.png"

        env:
          REPO_TOKEN: "${{ secrets.REPO_TOKEN }}"
