name: "example"
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Script Kit
        uses: johnlindquist/kit-action@main
        with:
          # The name of a script in your ./scripts dir
          script: "example-script"
          # Optional space-separated string arguments passed to each "await arg()"
          args: "https://johnlindquist.com/images/logo/john@2x.png 100 100"
          token: ${{ secrets.GITHUB_TOKEN }}
